CREATE TABLE user(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dong VARCHAR(4) NOT NULL,
    ho VARCHAR(4) NOT NULL,
    username VARCHAR(15) NOT NULL,
    pw VARCHAR(255) NOT NULL,
    phone1 VARCHAR(11) NOT NULL,
    phone2 VARCHAR(11) NOT NULL,
    movein DATETIME NOT NULL,
    isAdmin VARCHAR(1) NOT NULL DEFAULT 0
)